spring.application.name=api

spring.datasource.url=jdbc:h2:./db/database

# Usuario y contrasena de la base de datos
spring.datasource.username=sa
spring.datasource.password=

# Le indicamos a JPA/Hibernate que se encargue de generar el DDL
spring.jpa.hibernate.ddl-auto=create-drop

# Habilitamos la consola de H2
spring.h2.console.enabled=true

# Habilitamos los mensajes sql en el log
spring.jpa.show-sql=true


jwt.secret=mi_secreto_jwt_para_firmar_los_tokens_lo_pongo_asi_pa_que_no_sea_corto_12_le_23_pongo_numeros_sd23_y_letras
jwt.duration=1
jwt.refresh.duration=2