validation.unique.email=El correo electrónico ya está registrado.
validation.unique.username=El nombre de usuario ya está registrado.
validation.mismatch.password=Las contraseñas no coinciden.

validation.empty.email=El correo electrónico es obligatorio.
validation.empty.username=El correo electrónico es obligatorio.
validation.empty.name=El correo electrónico es obligatorio.
validation.empty.lastName=El correo electrónico es obligatorio.
validation.empty.password=La contraseña es obligatoria.

validation.invalid.email=El correo electrónico no tiene un formato válido.
validation.invalid.password=La contraseña debe tener al menos 8 caracteres.

validation.empty.title=El título es obligatorio.
validation.empty.description=La descripción es obligatoria.
validation.empty.category=La categoría es obligatoria.
validation.empty.steps=Los pasos son obligatorios.
validation.empty.step.name=El nombre del paso es obligatorio.
validation.empty.step.position=La posición del paso es obligatoria.
validation.empty.step.pictogram=El ID del pictograma ARASAAC es obligatorio.

validation.invalid.category=La categoría especificada no existe.
validation.invalid.steps=La secuencia debe tener al menos un paso.
validation.invalid.step.position=La posición del paso debe ser mayor a 0.
validation.invalid.step.name=El nombre del paso no puede estar vacío.
validation.invalid.step.pictogram=El ID del pictograma ARASAAC no es válido.
