validation.unique.email=El correo electrónico ya está registrado.
validation.unique.username=El nombre de usuario ya está registrado.
validation.mismatch.password=Las contraseñas no coinciden.

validation.empty.email=El correo electrónico es obligatorio.
validation.empty.username=El correo electrónico es obligatorio.
validation.empty.name=El correo electrónico es obligatorio.
validation.empty.lastName=El correo electrónico es obligatorio.
validation.empty.password=La contraseña es obligatoria.

validation.invalid.email=El correo electrónico no tiene un formato válido.
validation.invalid.password=La contraseña debe tener al menos 8 caracteres.